name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create Infinity Engine Mod Packages (.iemod and .zip)
        uses: ALIENQuake/CreateIEModZipPackage@master
        id: create_mod_package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Nightly builds
      - name: Upload artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: unique-artifacts
          path: |
            ${{ steps.create_mod_package.outputs.PackageBaseName }}.iemod
            ${{ steps.create_mod_package.outputs.PackageBaseName }}.zip
          if-no-files-found: error

      # Tagged releases
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.create_mod_package.outputs.PackageBaseName }}.iemod
            ${{ steps.create_mod_package.outputs.PackageBaseName }}.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
